"http://www.vim.org/htmldoc/options.html"
set nocompatible "Usa config por defecto de vim"
syntax on "Muchos colores"
set paste "No indentar codigo 'pasteado'"
set nobackup "No crea ficheros de backup *~"
set showcmd "Muestra comandos incompletos"
set ruler "Mestra siempre la pos. del cursor"
set number "Muestra no de lineas"
set tabstop=4 "Tabs de 4 espacios"
set encoding=utf-8 "Encoding"
set foldmethod=marker "folding manual"
